name = "starflow"
version = "0.0.1"

target = "erlang"

description = "A library for building stateful chains of LLM interactions!"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_httpc = ">= 3.0.0 and < 4.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
prng = ">= 3.0.3 and < 4.0.0"
